-- CreateTable
CREATE TABLE "public"."PROJECTS" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "CLIENT_NAME" TEXT,
    "BUDGET_HOURS" INTEGER,
    "IS_BILLABLE" BOOLEAN NOT NULL DEFAULT true,
    "IS_ARCHIVED" BOOLEAN NOT NULL DEFAULT false,
    "START_DATE" TIMESTAMP(3),
    "END_DATE" TIMESTAMP(3),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROJECTS_pkey" PRIMARY KEY ("ID")
);
