-- CreateTable
CREATE TABLE "public"."TIME_OFF_TYPES" (
    "ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "NAME" VARCHAR(50) NOT NULL,
    "IS_PAID" BOOLEAN NOT NULL DEFAULT true,
    "DESCRIPTION" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TIME_OFF_TYPES_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TIME_OFF_TYPES_NAME_key" ON "public"."TIME_OFF_TYPES"("NAME");
